# Welcome to Funktor & Serverless!
#
# This file is the main config file for your service.
# It's already configured to run Funktor, you just have to deploy it.
#
# For more info about Funktor:
#    TODO
#
# For more about serverless, check their docs:
#    docs.serverless.com
#
# Happy Coding!

# The name of your service. All your AWS resources will contain this name.
service: funktor-testbed

# This causes serverless to throw an error early if the config is bad, instead of waiting for CloudFormation to try and fail to deploy it.
configValidationMode: error

# Pin the serverless framework to the 2.x line
frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  environment: ${file(config/environment.yml)}
  versionFunctions: false # Reduces the amount of storage used since all Lambdas together are limited to 75GB
  iamRoleStatements:
    - ${file(config/iam_permissions/default_queue.yml)}
    - ${file(config/iam_permissions/incoming_job_queue.yml)}
    - ${file(config/iam_permissions/ssm.yml)}


custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${self:provider.stage, 'dev'}
  funktor: ${file(config/funktor.yml)}
  rubyLayer: ${file(config/ruby_layer.yml)}

package: ${file(config/package.yml)}

functions:
  IncomingJobHandler: ${file(config/function_definitions/incoming_job_handler.yml)}
  DefaultQueueHandler: ${file(config/function_definitions/default_queue_handler.yml)}
  RandomJobGenerator: ${file(config/function_definitions/random_job_generator.yml)}

resources:
  - ${file(config/resources/incoming_job_queue_user.yml)}
  - ${file(config/resources/cloudwatch_dashboard.yml)}
  - ${file(config/resources/default_queue.yml)}
  - ${file(config/resources/incoming_job_queue.yml)}

plugins:
  - serverless-ruby-layer
